language: cpp
dist: trusty
sudo: false
compiler: clang

script:
- cmake .
- cmake --build .
- cmake --build . --target check
- CLANG_FORMAT=clang-format-3.8 ./lint.sh
- git diff --exit-code

addons:
  apt:
    packages:
    - clang-format-3.8
