language: cpp
dist: trusty
sudo: false

matrix:
  include:
  - compiler: clang
    env:
    - CXXFLAGS=-fsanitize=address
    script:
    - lexer_source_commit=$(git --no-pager log -n 1 --pretty=format:%h -- 3rdparty/cmake-3.7.2/Source/cmListFileLexer.in.l)
    - lexer_generated_commit=$(git --no-pager log -n 1 --pretty=format:%h -- cmListFileLexer.c)
    - git merge-base --is-ancestor "${lexer_source_commit}" "${lexer_generated_commit}"
    - cmake .
    - make all check
    - ./cmake-format -i CMakeLists.txt -indent-rparen="" -indent="    "
    - git --no-pager diff --exit-code
  - script:
    - find . -not \( -path "./3rdparty" -prune \) -name '*.cpp' -o -name '*.h' | xargs clang-format -i
    - git --no-pager diff --exit-code
    compiler: none
    language: none
    addons:
      apt:
        packages:
        - clang-format-3.8
